services:
  frontend:
    image: microservices-frontend:1.0
    container_name: microservices-frontend-v2
    ports:
      - "8083:80"
    environment:
      FRONTEND_ENV: production
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend

  backend:
    image: microservices-backend:v2
    container_name: microservices-backend-v2
    ports:
      - "8084:8080"
    environment:
      APP_NAME: Snehal Microservices Backend V2
      APP_ENV: production
      PORT: "8080"
      DB_HOST: database
      DB_PORT: "5432"
      DB_NAME: microservices
      DB_USER: snehal
    depends_on:
      - database

  database:
    image: microservices-database:1.0
    container_name: microservices-database-v2
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: microservices
      POSTGRES_USER: snehal
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

secrets:
  db_password:
    file: ./secrets/db_password.txt

